package io.github.toomanylimits.wasmj.compiling.simple_structure.intrinsics.sandbox;

import io.github.toomanylimits.wasmj.compiling.compiler.CompilingSimpleInstructionVisitor;
import io.github.toomanylimits.wasmj.compiling.simple_structure.SimpleInstruction;
import io.github.toomanylimits.wasmj.compiling.simple_structure.SimpleModule;
import io.github.toomanylimits.wasmj.compiling.simple_structure.intrinsics.ClassGenCallback;
import org.objectweb.asm.MethodVisitor;

/**
 * Not generated by any WASM instruction in particular, but is emitted
 * sometimes when compiling to keep code cleaner.
 */
public class IncRefCount implements SimpleInstruction.Intrinsic {

    public static final IncRefCount INSTANCE = new IncRefCount();
    private IncRefCount() {}

    @Override
    public void atCallSite(SimpleModule module, MethodVisitor visitor, CompilingSimpleInstructionVisitor compilingVisitor) {
        if (!module.instance.limiter.countsMemory)
            throw new IllegalStateException("IncRefCount intrinsic should only be generated when the module counts memory - bug in compiler!");
        throw new UnsupportedOperationException("TODO");
    }

    @Override
    public ClassGenCallback classGenCallback() {
        return (module, classVisitor) -> {
            if (!module.instance.limiter.countsMemory)
                throw new IllegalStateException("IncRefCount intrinsic should only be generated when the module counts memory - bug in compiler!");
            throw new UnsupportedOperationException("TODO");
        };
    }
}
